export const QUOTES = [
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Move fast and break things.", author: "Mark Zuckerberg" },
  { text: "Software is eating the world.", author: "Marc Andreessen" },
  { text: "Competition is for losers.", author: "Peter Thiel" },
  { text: "Your margin is my opportunity.", author: "Jeff Bezos" },
  { text: "Build what's missing.", author: "Paul Graham" },
  { text: "Play long-term games.", author: "Naval Ravikant" },
  { text: "Launch too early, not too late.", author: "Reid Hoffman" },
  { text: "Work like hell.", author: "Elon Musk" },
  { text: "Focus is saying no.", author: "Steve Jobs" },
  { text: "Ideas are cheap, execution is everything.", author: "Casey Neistat" },
  { text: "Do things that don't scale.", author: "Paul Graham" },
  { text: "Fortune favors the bold.", author: "Julius Caesar" },
  { text: "Speed is the ultimate weapon.", author: "Sam Altman" },
  { text: "Default alive, not default dead.", author: "Paul Graham" },
  { text: "Make something people want.", author: "Y Combinator" },
  { text: "Ship early, ship often.", author: "Silicon Valley proverb" },
  { text: "Cash flow is king.", author: "Jeff Bezos" },
  { text: "Think different.", author: "Apple" },
  { text: "Zero to one, not one to n.", author: "Peter Thiel" },
];
